server:
  port: 18080
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
jwt:
  # openssl rand -base64 256
  secret: gx4SN/4gh6QPvLfVWCW8Aoo4l2n66d2338IwXyu1koDT1W94XS35OZJPYkA2IIMMgmlz96LCHSNc8jLYuzwB1IreKOZz2TZhsWODfjHAS9bYlduniCUSuSPZ5/OP15O63fn1kN1N5w64frpyWcWbTtiCgLMkJpnfjmqFMAr7fgcOGyt2rmunvFYni9T78Q4fn/0gpx3qm8zXw3oBbFb1Ge9Wnh1UCSapXd/EzLau3iaXqp9f+8FHmSCo9vbEaRSRMPHdcpnB4WKHKySE/BCNSsWM+kHmHyrAbvKErPCz2XXMnIalUoAtquq03LnmYjrBHyI230VcYEVzGmzLOTsSJw==
  access_token:
    expiration: 604800
  refresh_token:
    expiration: 604800
file:
#  windows本地，文件在项目根目录的files文件夹下，请根据自己的项目路径修改
  upload-path: D:\pku_lessons\agile_development\student_scholarship\student_management_back_end\files
  allowed-types: pdf
  max-size: 10485760   # 10MB
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
#    password: jK7-iT3.rV8!vQ7=eR7=sE7]rC3%e  #(如果有密码的话)
#  数据库连接,连接到阿里云服务器上的数据库
  datasource:
    url: jdbc:mysql://39.101.65.178:3306/stu_mgmt
    username: stu_mgmt
    password: cWf2DdxmNzKzEJ2C
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
